JAVA_HOME=/usr/java/jdk1.8.0_144
HADOOP_CONF_DIR=/etc/hadoop/conf
SPARK_LOCAL_DIRS=/home/dev/liuh/STREAM/spark/data/spark_local_dir
SPARK_CONF_DIR=${SPARK_HOME}/conf
SPARK_DRIVER_MEMORY=2G
SPARK_MASTER_HOST=10.4.39.34
SPARK_MASTER_PORT=7077
SPARK_MASTER_WEBUI_PORT=8091
SPARK_WORKER_CORES=16
SPARK_WORKER_MEMORY=5g
SPARK_WORKER_PORT=8092
SPARK_WORKER_WEBUI_PORT=8093
SPARK_DAEMON_JAVA_OPTS="-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=xxx:2181 $SPARK_DAEMON_JAVA_OPTS"
SPARK_LOG_DIR=spark/logs
SPARK_PID_DIR=spark/tmp
